### ISSUE TITLE
device registering

### ISSUE THREAD

**Issue by chegewara** [MrBuddyCasino/alexa-auth#2]
During device registration on first page that is asking amazon credentials email and password are sent with plain text and i think those data are not important to register device, so my advice is to not give real credentials.

EDIT its not like that i dont trust MrBuddyCasino, just sending credentials with plain text from my devices

**Comment by mano1979** [comment]
I also found that the MAC address that is needed to create the authorization code does not have to match the real MAC address.

I used my allready configured code on a fresh esp32 and it just worked.

**Comment by chegewara** [comment]
https://github.com/MrBuddyCasino/ESP32_Alexa/issues/24

**Comment by MrBuddyCasino** [comment]
U sure? The auth service should never see credentials, they go directly to Amazon if I remember right.

**Comment by chegewara** [comment]
From this link all data are in plain text:
https://alexa.boeckling.net/add_device
Its first redirect link after providing device ID.
