### ISSUE TITLE
I have a error and I can't resolve it！

### ISSUE THREAD

**Issue by fengfeng0328** [MrBuddyCasino/alexa-auth#5]
zifeng@os:~/sources/pro/alexa-auth/target/release$ ./alexa-auth 
🔧  Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 8
    => secret key: generated
    => limits: forms = 32KiB
    => tls: disabled
🛰  Mounting '/':
    => GET /
    => GET /auth/refresh/<refresh_token>
    => POST /add_device
    => GET /consent
    => GET /return?<return_params>
Error: Rocket failed to launch due to an I/O error.
thread 'main' panicked at 'Address already in use (os error 98)', /home/zifeng/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.3.16/src/error.rs:204:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by MrBuddyCasino** [comment]
"Address already in use" means the port is probably already in use. Find out with your OS specific tools (netstat, lsof etc.).

**Comment by fengfeng0328** [comment]
Thank you, I managed to solve this problem based on your tips
